SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE FUNCTION [dbo].[dbaudf_RestoreHeader] (@full_backup_path [nvarchar] (max))
RETURNS TABLE (
[BackupName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupType] [smallint] NULL,
[ExpirationDate] [datetime] NULL,
[Compressed] [bit] NULL,
[Position] [smallint] NULL,
[DeviceType] [tinyint] NULL,
[UserName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServerName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseVersion] [int] NULL,
[DatabaseCreationDate] [datetime] NULL,
[BackupSize] [numeric] (20, 0) NULL,
[FirstLSN] [numeric] (25, 0) NULL,
[LastLSN] [numeric] (25, 0) NULL,
[CheckpointLSN] [numeric] (25, 0) NULL,
[DatabaseBackupLSN] [numeric] (25, 0) NULL,
[BackupStartDate] [datetime] NULL,
[BackupFinishDate] [datetime] NULL,
[SortOrder] [smallint] NULL,
[CodePage] [smallint] NULL,
[UnicodeLocaleId] [int] NULL,
[UnicodeComparisonStyle] [int] NULL,
[CompatibilityLevel] [tinyint] NULL,
[SoftwareVendorId] [int] NULL,
[SoftwareVersionMajor] [int] NULL,
[SoftwareVersionMinor] [int] NULL,
[SoftwareVersionBuild] [int] NULL,
[MachineName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flags] [int] NULL,
[BindingID] [uniqueidentifier] NULL,
[RecoveryForkID] [uniqueidentifier] NULL,
[Collation] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyGUID] [uniqueidentifier] NULL,
[HasBulkLoggedData] [bit] NULL,
[IsSnapshot] [bit] NULL,
[IsReadOnly] [bit] NULL,
[IsSingleUser] [bit] NULL,
[HasBackupChecksums] [bit] NULL,
[IsDamaged] [bit] NULL,
[BeginsLogChain] [bit] NULL,
[HasIncompleteMetaData] [bit] NULL,
[IsForceOffline] [bit] NULL,
[IsCopyOnly] [bit] NULL,
[FirstRecoveryForkID] [uniqueidentifier] NULL,
[ForkPointLSN] [numeric] (25, 0) NULL,
[RecoveryModel] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DifferentialBaseLSN] [numeric] (25, 0) NULL,
[DifferentialBaseGUID] [uniqueidentifier] NULL,
[BackupTypeDescription] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackupSetGUID] [uniqueidentifier] NULL,
[CompressedBackupSize] [bigint] NULL,
[Containment] [bit] NULL)
WITH EXECUTE AS CALLER
EXTERNAL NAME [Virtuoso.Operations.CLRTools].[Virtuoso.Operations.UserDefinedFunctions].[headers]
GO
