SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[dbasp_GetErrorInfo] (@AsTable BIT = 0)
AS
	IF @AsTable = 0
	BEGIN
		DECLARE	@ERROR_NUMBER			INT
			,@ERROR_SEVERITY		INT
			,@ERROR_STATE			INT
			,@ERROR_LINE			INT
			,@ERROR_PROCEDURE		VarChar(max)
			,@ERROR_MESSAGE			VarChar(max)


		SELECT	@ERROR_NUMBER			= ERROR_NUMBER()
			,@ERROR_SEVERITY		= ERROR_SEVERITY()
			,@ERROR_STATE			= ERROR_STATE()
			,@ERROR_LINE			= ERROR_LINE ()
			,@ERROR_PROCEDURE		= ERROR_PROCEDURE()
			,@ERROR_MESSAGE			= ERROR_MESSAGE()


		RAISERROR ('@ERROR_NUMBER	:%d',-1,-1,@ERROR_NUMBER) WITH NOWAIT
		RAISERROR ('@ERROR_SEVERITY	:%d',-1,-1,@ERROR_SEVERITY) WITH NOWAIT
		RAISERROR ('@ERROR_STATE	:%d',-1,-1,@ERROR_STATE) WITH NOWAIT
		RAISERROR ('@ERROR_LINE		:%d',-1,-1,@ERROR_LINE) WITH NOWAIT
		RAISERROR ('@ERROR_PROCEDURE	:%s',-1,-1,@ERROR_PROCEDURE) WITH NOWAIT
		RAISERROR ('@ERROR_MESSAGE	:%s',-1,-1,@ERROR_MESSAGE) WITH NOWAIT


	END
	ELSE
		SELECT	ERROR_NUMBER() AS ErrorNumber
			,ERROR_SEVERITY() AS ErrorSeverity
			,ERROR_STATE() AS ErrorState
			,ERROR_LINE () AS ErrorLine
			,ERROR_PROCEDURE() AS ErrorProcedure
			,ERROR_MESSAGE() AS ErrorMessage;
GO
GRANT EXECUTE ON  [dbo].[dbasp_GetErrorInfo] TO [public]
GO
